#!/usr/bin/env bash
# While loop 1..10 with if/elif/else messaging
i=1; while [ "$i" -le 10 ]; do
  if   [ "$i" -eq 4 ]; then echo "bad luck"
  elif [ "$i" -eq 8 ]; then echo "good luck"
  else echo "Best School"
  fi
  i=$((i+1))
done
